# Generated by Django 4.1 on 2022-10-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pria'), (2, 'Wanita')], null=True),
        ),
    ]
