# Generated by Django 4.1 on 2022-11-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegulasiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Produk Hukum'), (2, 'Rapat Koordinasi'), (3, 'Paparan')], null=True)),
                ('tahun', models.IntegerField(blank=True, max_length=4, null=True)),
                ('kategori', models.PositiveIntegerField(blank=True, choices=[(1, 'Undang-Undang'), (2, 'Perancangan Undang-Undang'), (3, 'Peraturan Pemerintah'), (4, 'Peraturan Presiden'), (6, 'Peraturan Mentri'), (7, 'Keputusan Mentri'), (8, 'Keputusan Deputi'), (9, 'Peraturan Terkait'), (10, 'Petunjuk Pelaksanaan'), (11, 'Surat Edaran')], null=True)),
                ('documentFile', models.FileField(upload_to='documents/regulasi/')),
                ('created_by', models.CharField(blank=True, max_length=25, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=25, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'regulasi_data',
                'db_table': 'regulasi_data',
            },
        ),
    ]
