# Generated by Django 4.1 on 2022-11-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulasimodel',
            name='kategori',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Undang-Undang'), (2, 'Perancangan Undang-Undang'), (3, 'Peraturan Pemerintah'), (4, 'Peraturan Presiden'), (5, 'Keputusan dan Intruksi Presiden'), (6, 'Peraturan Mentri'), (7, 'Keputusan Mentri'), (8, 'Keputusan Deputi'), (9, 'Peraturan Terkait'), (10, 'Petunjuk Pelaksanaan'), (11, 'Surat Edaran')], null=True),
        ),
    ]
