# Generated by Django 4.1 on 2022-11-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulasi', '0002_alter_regulasimodel_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulasimodel',
            name='tahun',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
