# Generated by Django 4.1 on 2022-11-04 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koperasi', '0001_initial'),
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkmodel',
            name='kopid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='koperasi.koperasimodel'),
        ),
    ]
