# Generated by Django 4.1 on 2022-11-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_produkmodel_kopid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetDemandProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpd_nmprod', models.CharField(max_length=150)),
                ('dpd_bulan', models.PositiveIntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Maret'), (4, 'April'), (5, 'Mei'), (6, 'Juni'), (7, 'Juli'), (8, 'Agustus'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Desember')])),
                ('dpd_tahun', models.IntegerField()),
                ('dpd_demand', models.IntegerField()),
                ('dpd_produksi', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'det_demand_prod',
                'db_table': 'det_demand_prod',
            },
        ),
        migrations.CreateModel(
            name='DetDemandSup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsp_jensup', models.CharField(choices=[('retail', 'Retail'), ('pemasok', 'Pemasok')], max_length=150)),
                ('dsp_bulan', models.PositiveIntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Maret'), (4, 'April'), (5, 'Mei'), (6, 'Juni'), (7, 'Juli'), (8, 'Agustus'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Desember')])),
                ('dsp_tahun', models.IntegerField()),
                ('dsp_demand', models.IntegerField()),
                ('dsp_produksi', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'det_demand_supp',
                'db_table': 'det_demand_supp',
            },
        ),
        migrations.CreateModel(
            name='ProdukUMKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komoditi', models.CharField(max_length=150)),
                ('volume', models.CharField(max_length=150)),
                ('satuan', models.CharField(max_length=150)),
                ('harga', models.IntegerField()),
                ('total', models.IntegerField()),
                ('fotoprod', models.ImageField(blank=True, null=True, upload_to='produk/')),
            ],
            options={
                'verbose_name_plural': 'produk_umkm',
                'db_table': 'produk_umkm',
            },
        ),
        migrations.AlterModelOptions(
            name='produkmodel',
            options={'verbose_name_plural': 'produk_kop'},
        ),
        migrations.AlterModelTable(
            name='produkmodel',
            table='produk_kop',
        ),
    ]
