# Generated by Django 4.1 on 2022-11-14 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umkmdata', '0001_initial'),
        ('produk', '0003_detdemandprod_detdemandsup_produkumkm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkumkm',
            name='umkmid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umkmdata.umkmmodel'),
        ),
        migrations.AddField(
            model_name='detdemandsup',
            name='dsp_umkm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umkmdata.umkmmodel'),
        ),
        migrations.AddField(
            model_name='detdemandprod',
            name='dpd_umkm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umkmdata.umkmmodel'),
        ),
    ]
