# Generated by Django 4.1 on 2022-11-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0004_produkumkm_umkmid_detdemandsup_dsp_umkm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detdemandprod',
            old_name='dpd_umkm',
            new_name='umkmid',
        ),
        migrations.RenameField(
            model_name='detdemandsup',
            old_name='dsp_umkm',
            new_name='umkmid',
        ),
    ]
