# Generated by Django 4.1 on 2022-11-15 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0006_detpenilaiansupp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detpenilaiansupp',
            old_name='harga',
            new_name='dps_harga',
        ),
        migrations.RenameField(
            model_name='detpenilaiansupp',
            old_name='kualitas',
            new_name='dps_kualitas',
        ),
        migrations.RenameField(
            model_name='detpenilaiansupp',
            old_name='nm_supp',
            new_name='dps_nm_supp',
        ),
        migrations.RenameField(
            model_name='detpenilaiansupp',
            old_name='pengiriman',
            new_name='dps_pengiriman',
        ),
    ]
