# Generated by Django 4.1 on 2022-11-04 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import koperasi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KoperasiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('du_ftkop', models.ImageField(blank=True, null=True, upload_to=koperasi.models.KoperasiModel.profile_upto)),
                ('du_nakop', models.CharField(max_length=255)),
                ('du_alkop', models.TextField(blank=True, max_length=250, null=True)),
                ('du_jenkop', models.PositiveIntegerField(choices=[(1, 'Konsumen'), (2, 'Simpan Pinjam'), (3, 'Jasa'), (4, 'Produsen'), (5, 'Pemasaran')])),
                ('du_bhkkop', models.CharField(blank=True, max_length=150, null=True)),
                ('da_nmketua', models.CharField(blank=True, max_length=250, null=True)),
                ('da_nmsekre', models.CharField(blank=True, max_length=250, null=True)),
                ('da_nmbenda', models.CharField(blank=True, max_length=250, null=True)),
                ('da_nmpngla', models.CharField(blank=True, max_length=250, null=True)),
                ('da_nmpngws', models.CharField(blank=True, max_length=250, null=True)),
                ('da_jmlaggt', models.IntegerField(blank=True, default=0, null=True)),
                ('da_jmlkrywn', models.IntegerField(blank=True, default=0, null=True)),
                ('da_tglrat', models.DateField()),
                ('da_jmlhdrrat', models.IntegerField(blank=True, default=0, null=True)),
                ('pj_jassimkop', models.FileField(blank=True, null=True, upload_to=koperasi.models.KoperasiModel.documents_upto)),
                ('pj_jaspinkop', models.FileField(blank=True, null=True, upload_to=koperasi.models.KoperasiModel.documents_upto)),
                ('pj_produngkop', models.FileField(blank=True, null=True, upload_to=koperasi.models.KoperasiModel.documents_upto)),
                ('rkp_lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('rkp_long', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('rkp_tglinput', models.DateField()),
                ('rkp_nmpmlk', models.CharField(max_length=255)),
                ('rkp_nikpmlk', models.IntegerField(max_length=255)),
                ('rkp_nibkop', models.IntegerField(max_length=255)),
                ('doc_ketuakop', models.FileField(blank=True, null=True, upload_to=koperasi.models.KoperasiModel.documents_upto)),
                ('doc_sekrekop', models.FileField(blank=True, null=True, upload_to=koperasi.models.KoperasiModel.documents_upto)),
                ('doc_bendakop', models.FileField(blank=True, null=True, upload_to=koperasi.models.KoperasiModel.documents_upto)),
                ('doc_pnglakop', models.FileField(blank=True, null=True, upload_to=koperasi.models.KoperasiModel.documents_upto)),
                ('doc_pngwskop', models.FileField(blank=True, null=True, upload_to=koperasi.models.KoperasiModel.documents_upto)),
                ('created_by', models.CharField(blank=True, max_length=25, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=25, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('dt_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'koperasi_data',
                'db_table': 'koperasi_data',
            },
        ),
    ]
