# Generated by Django 4.1 on 2022-11-05 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userprofile_gender'),
        ('koperasi', '0002_alter_koperasimodel_rkp_nibkop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koperasimodel',
            name='dt_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='userprofile.userprofile'),
        ),
    ]
