# Generated by Django 4.1 on 2022-11-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koperasi', '0003_alter_koperasimodel_dt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koperasimodel',
            name='da_tglrat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='koperasimodel',
            name='du_alkop',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='koperasimodel',
            name='rkp_nmpmlk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='koperasimodel',
            name='rkp_tglinput',
            field=models.DateField(blank=True, null=True),
        ),
    ]
