# Generated by Django 4.1 on 2022-12-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koperasi', '0004_alter_koperasimodel_da_tglrat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koperasimodel',
            name='du_jenkop',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Konsumen'), (2, 'Simpan Pinjam'), (3, 'Jasa'), (4, 'Produsen'), (5, 'Pemasaran')], null=True),
        ),
    ]
