# Generated by Django 4.1 on 2022-12-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koperasi', '0006_alter_koperasimodel_du_jenkop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koperasimodel',
            name='da_jmlaggt',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='koperasimodel',
            name='da_jmlhdrrat',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='koperasimodel',
            name='da_jmlkrywn',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='koperasimodel',
            name='rkp_nibkop',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='koperasimodel',
            name='rkp_nikpmlk',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
