# Generated by Django 4.1 on 2023-01-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koperasi', '0007_alter_koperasimodel_da_jmlaggt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriIPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_var', models.CharField(blank=True, max_length=250, null=True)),
                ('ipkat', models.CharField(blank=True, choices=[('tata-kelola', 'TATA KELOLA'), ('profil-risiko', 'PROFIL RISIKO')], default='tata-kelola', max_length=200, null=True)),
                ('ipsubkat', models.CharField(blank=True, choices=[('prinsip-koperasi', 'PRINSIP KOPERASI'), ('kelembagaan', 'KELEMBAGAAN'), ('manajemen', 'MANAJEMEN'), ('risiko-operasional', 'Risiko Operasional'), ('risiko-kepatuhan', 'Risiko Kepatuhan'), ('risiko-likuiditas', 'Risiko Likuiditas'), ('kpmr-pinjaman', 'Kualitas Penerapan Manajemen Risiko Pinjaman/pembiayaan'), ('kpmr-operasional', 'Kualitas Penerapan Manajemen Risiko Operasional'), ('kpmr-kepatuhan', 'Kualitas Penerapan Manajemen Risiko Kepatuhan'), ('kpmr-likuiditas', 'Kualitas Penerapan Manajemen Risiko Likuiditas')], default='prinsip-koperasi', max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'kategori_ip',
                'db_table': 'kategori_ip',
            },
        ),
    ]
