# Generated by Django 4.1 on 2023-01-31 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koperasi', '0008_kategoriipmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPPatuhModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_ukur', models.CharField(blank=True, max_length=255, null=True)),
                ('dok_pendukung', models.CharField(blank=True, max_length=255, null=True)),
                ('temuan', models.CharField(blank=True, max_length=255, null=True)),
                ('kat_var', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='koperasi.kategoriipmodel')),
            ],
            options={
                'verbose_name_plural': 'dp_patuh',
                'db_table': 'dp_patuh',
            },
        ),
    ]
