# Generated by Django 4.1 on 2023-02-03 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koperasi', '0009_dppatuhmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailDpPatuh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_dp', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('choose_dp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koperasi.dppatuhmodel')),
                ('choose_kop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koperasi.koperasimodel')),
            ],
        ),
    ]
