# Generated by Django 4.1 on 2022-11-14 03:54

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import umkmdata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0002_alter_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisEnergi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.CharField(blank=True, default='', max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='judul', unique=True)),
            ],
            options={
                'verbose_name_plural': 'jenis_energi',
                'db_table': 'jenis_energi',
            },
        ),
        migrations.CreateModel(
            name='JenisTenagaKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.CharField(blank=True, default='', max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='judul', unique=True)),
            ],
            options={
                'verbose_name_plural': 'jenis_tenaga_kerja',
                'db_table': 'jenis_tenaga_kerja',
            },
        ),
        migrations.CreateModel(
            name='Pendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.CharField(blank=True, default='', max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='judul', unique=True)),
            ],
            options={
                'verbose_name_plural': 'pendidikan_data',
                'db_table': 'pendidikan_data',
            },
        ),
        migrations.CreateModel(
            name='TipeFasilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.CharField(blank=True, default='', max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='judul', unique=True)),
            ],
            options={
                'verbose_name_plural': 'tipe_fasilitas',
                'db_table': 'tipe_fasilitas',
            },
        ),
        migrations.CreateModel(
            name='TipePerijinan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.CharField(blank=True, default='', max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='judul', unique=True)),
            ],
            options={
                'verbose_name_plural': 'tipe_perijinan',
                'db_table': 'tipe_perijinan',
            },
        ),
        migrations.CreateModel(
            name='UmkmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pu_noaggta', models.CharField(blank=True, max_length=250, null=True)),
                ('pu_nmpmlk', models.CharField(max_length=250)),
                ('pu_aldmisi', models.TextField(max_length=255)),
                ('pu_noktp', models.IntegerField()),
                ('pu_notlp', models.IntegerField()),
                ('pu_email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('du_ftusha', models.ImageField(blank=True, null=True, upload_to=umkmdata.models.UmkmModel.profile_upto)),
                ('du_nmusha', models.CharField(max_length=255)),
                ('du_alusha', models.TextField(max_length=255)),
                ('du_btkusha', models.PositiveIntegerField(choices=[(1, 'Perorangan'), (2, 'CV'), (3, 'UD'), (4, 'Koperasi'), (5, 'Lainnya')])),
                ('du_bdgusha', models.PositiveIntegerField(choices=[(1, 'Makanan dalam Kemasan'), (2, 'Minuman dalam Kemasan'), (3, 'Kerajinan'), (4, 'Perdagangan'), (5, 'Jasa'), (6, 'Lainnya')])),
                ('du_thnbrdr', models.IntegerField()),
                ('du_lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('du_long', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('dtu_tujuan', models.CharField(blank=True, max_length=250, null=True)),
                ('dtu_omzetthn', models.IntegerField(blank=True, null=True)),
                ('dtu_totalthn', models.IntegerField(blank=True, null=True)),
                ('dtu_skalausha', models.PositiveIntegerField(choices=[(1, 'Mikro'), (2, 'Kecil'), (3, 'Menengah')])),
                ('dtu_wktutggu', models.IntegerField(blank=True, null=True)),
                ('dtu_bypsnunit', models.IntegerField(blank=True, null=True)),
                ('dtu_bysmpunit', models.IntegerField(blank=True, null=True)),
                ('dtu_kltsharga', models.SmallIntegerField(blank=True, null=True)),
                ('dtu_kltskirim', models.SmallIntegerField(blank=True, null=True)),
                ('dtu_hrgakirim', models.SmallIntegerField(blank=True, null=True)),
                ('dtu_uraimslh', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=25, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=25, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('dt_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='userprofile.userprofile')),
            ],
            options={
                'verbose_name_plural': 'umkm_data',
                'db_table': 'umkm_data',
            },
        ),
        migrations.CreateModel(
            name='DetailTenagaKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jml_org', models.IntegerField(blank=True, null=True)),
                ('jenis_tngkrj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umkmdata.jenistenagakerja')),
                ('pendidikan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umkmdata.pendidikan')),
                ('umkmid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umkmdata.umkmmodel')),
            ],
            options={
                'verbose_name_plural': 'detail_tenaga_kerja',
                'db_table': 'detail_tenaga_kerja',
            },
        ),
        migrations.CreateModel(
            name='DetailPerijinan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_ijin', models.IntegerField(blank=True, null=True)),
                ('tgl_ijin', models.DateField(blank=True, null=True)),
                ('tipe_ijin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umkmdata.tipeperijinan')),
                ('umkmid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umkmdata.umkmmodel')),
            ],
            options={
                'verbose_name_plural': 'detail_perijinan',
                'db_table': 'detail_perijinan',
            },
        ),
        migrations.CreateModel(
            name='DetailPelatihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_pelat', models.CharField(blank=True, max_length=250, null=True)),
                ('tmpt_pelat', models.CharField(blank=True, max_length=250, null=True)),
                ('thn_pelat', models.IntegerField(blank=True, null=True)),
                ('umkmid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umkmdata.umkmmodel')),
            ],
            options={
                'verbose_name_plural': 'detail_pelatihan',
                'db_table': 'detail_pelatihan',
            },
        ),
        migrations.CreateModel(
            name='DetailMesin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_mesin', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_mesin', models.CharField(blank=True, max_length=250, null=True)),
                ('jml_mesin', models.IntegerField(blank=True, null=True)),
                ('umkmid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umkmdata.umkmmodel')),
            ],
            options={
                'verbose_name_plural': 'detail_alat_mesin',
                'db_table': 'detail_alat_mesin',
            },
        ),
        migrations.CreateModel(
            name='DetailFasilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_fasi', models.CharField(blank=True, max_length=250, null=True)),
                ('thn_fasi', models.IntegerField(blank=True, null=True)),
                ('tipe_fasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umkmdata.tipefasilitas')),
                ('umkmid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umkmdata.umkmmodel')),
            ],
            options={
                'verbose_name_plural': 'detail_fasilitas',
                'db_table': 'detail_fasilitas',
            },
        ),
        migrations.CreateModel(
            name='DetailEnergi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kapasitas', models.IntegerField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
                ('jen_energi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umkmdata.jenisenergi')),
                ('umkmid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umkmdata.umkmmodel')),
            ],
            options={
                'verbose_name_plural': 'detail_pakai_energi',
                'db_table': 'detail_pakai_energi',
            },
        ),
        migrations.CreateModel(
            name='DetailBahanBaku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jen_bhbaku', models.CharField(max_length=200)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('nilai', models.IntegerField(blank=True, null=True)),
                ('asalBB', models.CharField(blank=True, max_length=200, null=True)),
                ('umkmid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umkmdata.umkmmodel')),
            ],
            options={
                'verbose_name_plural': 'detail_bahan_baku',
                'db_table': 'detail_bahan_baku',
            },
        ),
    ]
