# Generated by Django 4.1 on 2022-11-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umkmdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umkmmodel',
            old_name='dtu_totalthn',
            new_name='dtu_totalaset',
        ),
    ]
