# Generated by Django 4.1 on 2022-12-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkmdata', '0002_rename_dtu_totalthn_umkmmodel_dtu_totalaset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umkmmodel',
            name='du_bdgusha',
            field=models.PositiveIntegerField(choices=[(1, 'Makanan dalam Kemasan'), (2, 'Minuman dalam Kemasan'), (3, 'Kerajinan'), (4, 'Perdagangan'), (5, 'Jasa'), (6, 'Lainnya')], default=1),
        ),
        migrations.AlterField(
            model_name='umkmmodel',
            name='du_btkusha',
            field=models.PositiveIntegerField(choices=[(1, 'Perorangan'), (2, 'CV'), (3, 'UD'), (4, 'Koperasi'), (5, 'Lainnya')], default=1),
        ),
    ]
