# Generated by Django 4.1 on 2022-12-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkmdata', '0003_alter_umkmmodel_du_bdgusha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umkmmodel',
            name='dtu_skalausha',
            field=models.PositiveIntegerField(choices=[(1, 'Mikro'), (2, 'Kecil'), (3, 'Menengah')], default=1),
        ),
        migrations.AlterField(
            model_name='umkmmodel',
            name='du_thnbrdr',
            field=models.IntegerField(default=2000),
        ),
    ]
