# Generated by Django 4.1 on 2022-12-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkmdata', '0004_alter_umkmmodel_dtu_skalausha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umkmmodel',
            name='dtu_bypsnunit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='umkmmodel',
            name='dtu_bysmpunit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='umkmmodel',
            name='dtu_omzetthn',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='umkmmodel',
            name='dtu_totalaset',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='umkmmodel',
            name='dtu_wktutggu',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='umkmmodel',
            name='du_thnbrdr',
            field=models.BigIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='umkmmodel',
            name='pu_noktp',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='umkmmodel',
            name='pu_notlp',
            field=models.BigIntegerField(),
        ),
    ]
