# Generated by Django 4.1 on 2022-12-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkmdata', '0006_bentukusaha_bidangusaha_remove_umkmmodel_du_bdgusha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umkmmodel',
            name='du_bdgusha',
            field=models.ManyToManyField(blank=True, null=True, to='umkmdata.bidangusaha'),
        ),
        migrations.AlterField(
            model_name='umkmmodel',
            name='du_btkusha',
            field=models.ManyToManyField(blank=True, null=True, to='umkmdata.bentukusaha'),
        ),
    ]
