# Generated by Django 4.1 on 2023-01-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkmdata', '0007_alter_umkmmodel_du_bdgusha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umkmmodel',
            name='du_bdgusha',
            field=models.ManyToManyField(blank=True, to='umkmdata.bidangusaha'),
        ),
        migrations.AlterField(
            model_name='umkmmodel',
            name='du_btkusha',
            field=models.ManyToManyField(blank=True, to='umkmdata.bentukusaha'),
        ),
    ]
