# Generated by Django 4.1 on 2023-02-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0002_alter_keuanganmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_bilanghpp',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_byair',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_byasuran',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_byatulis',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_byaudit',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_bydiklat',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_byjaladin',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_bykarylain',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_bykeulain',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_bylistrik',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_byopslain',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_byorglain',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_bypajak',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_bypend',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_bypiutang',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_bypmbina',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_byrptangg',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_byrptpeng',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_bytelp',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_bytransdin',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_gjkaryawan',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_honorpeng',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_jasbank',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_jasimp',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_jasimpjang',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_jasimpkhus',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_jasimplain',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_konsumsi',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpb_tunjangan',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpe_cadresk',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpe_donasi',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpe_modpnyt',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpe_simppkk',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpe_simpwjb',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpk_bbymbyr',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpk_hutlain',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpk_hutush',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpk_simpberj',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpk_simpsuk',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpp_pendadm',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpp_pendjas',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpp_pendlain',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lpp_pendtko',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lps_akpbngn',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lps_akpinvkntr',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lps_aslancar',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lps_astdklcr',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lps_bank',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lps_bbmuka',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lps_bngn',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lps_invenkntr',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lps_kas',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lps_pendrima',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lps_persdbrg',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lps_persdkon',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lps_pinjang',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lps_pinjcet',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lps_piusha',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lps_piutagih',
        ),
        migrations.RemoveField(
            model_name='keuanganmodel',
            name='lps_tanah',
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_asetlancr',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_asetprod',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_asetthnlalu',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_astliquid',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_atmr',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_bbnperkop',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_bbnusaha',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_biayaoper',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_cadrisk',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_danain',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_dninthnlalu',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_hasilthnlalu',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_kasbank',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_modalthnlalu',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_modpinjanggt',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_modtimbang',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_pendoper',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_pendutama',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_pjmanggta',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_pjmbmslh',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_pnjmberi',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_ptsneto',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_shukotor',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_shupjk',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_simpanggtin',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_simppokok',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_simpwajib',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_totalpendt',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_totalsimpin',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_totaset',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_totmdlsdr',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_totpiutng',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_wjbjngkapjg',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keuanganmodel',
            name='lpk_wjblncar',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
