# Generated by Django 4.1 on 2022-10-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySetupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compName', models.CharField(max_length=100)),
                ('compLogo', models.ImageField(blank=True, null=True, upload_to='company/logo/')),
                ('compDesc', models.TextField(max_length=250, null=True)),
                ('compAddr', models.TextField(blank=True, max_length=250, null=True)),
                ('compPhone', models.CharField(blank=True, max_length=30, null=True)),
                ('compEmail', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('compFb', models.CharField(max_length=150)),
                ('compIg', models.CharField(max_length=150)),
                ('compWeb', models.CharField(max_length=150)),
                ('compAdm1', models.CharField(blank=True, max_length=30, null=True)),
                ('compAdm2', models.CharField(blank=True, max_length=30, null=True)),
                ('partName', models.CharField(max_length=100)),
                ('partLogo', models.ImageField(blank=True, null=True, upload_to='partner/logo/')),
                ('partDesc', models.TextField(max_length=250, null=True)),
                ('partAddr', models.TextField(blank=True, max_length=250, null=True)),
                ('created_by', models.CharField(blank=True, max_length=25, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=25, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
