# Generated by Django 4.1 on 2022-10-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companysetup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysetupmodel',
            name='compAddr',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='companysetupmodel',
            name='compDesc',
            field=models.TextField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='companysetupmodel',
            name='partAddr',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='companysetupmodel',
            name='partDesc',
            field=models.TextField(max_length=350, null=True),
        ),
    ]
