# Generated by Django 4.1 on 2022-11-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companysetup', '0002_alter_companysetupmodel_compaddr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetupmodel',
            name='compAdmFt1',
            field=models.ImageField(blank=True, null=True, upload_to='company/adm/'),
        ),
        migrations.AddField(
            model_name='companysetupmodel',
            name='compAdmFt2',
            field=models.ImageField(blank=True, null=True, upload_to='company/adm/'),
        ),
        migrations.AddField(
            model_name='companysetupmodel',
            name='compAdmNm1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='companysetupmodel',
            name='compAdmNm2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
