# Generated by Django 4.1 on 2022-11-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companysetup', '0003_companysetupmodel_compadmft1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCenterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scName', models.CharField(max_length=100)),
                ('scSubjek', models.CharField(max_length=100)),
                ('scPhone', models.CharField(blank=True, max_length=30, null=True)),
                ('scEmail', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('scMsgs', models.TextField(max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'support_center_data',
                'db_table': 'support_center_data',
            },
        ),
    ]
