# Generated by Django 4.1 on 2022-11-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companysetup', '0004_supportcentermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportcentermodel',
            name='scEmail',
            field=models.EmailField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supportcentermodel',
            name='scMsgs',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supportcentermodel',
            name='scPhone',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
